### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by guyou**
Please, consider my translation into french.

PS: is it possible to quickly upload an enhanced application to GooglePlay? My daughter does not read english nor spanish and we are far from a computer able to rebuild the application. As I've just bought the Beetle, I would be happy to let her play with it.

### CODE REVIEW

**Comment by yamidragut** [comment]
Hi guyou,

Thank you very much for your French translation! Right now I am on vacations, so until the next week at least I can not upload a new version to the Google Play. Sorry for the inconvenience. I will upload it at soon as possible. 

Thanks again!

**Comment by yamidragut** [comment]
Hi goyou, 

Finally I was able to going back to programming a little of RoboPad. I have tried your pull request, but you have some errors in the code. You have to put the escape character \ before the apostrophe in the following strings:

:RoboPad:processDebugResources Position 1 : Apostrophe not preceded by \ (in Si tu me presses, j'activerais ou désactiverais le mode de fuite de la lumière)
 Position 1 : Apostrophe not preceded by \ (in Si tu me presses, j'activerais ou désactiverais le mode de suivi de ligne)
 Position 1 : Apostrophe not preceded by \ (in Si tu me presses, j'activerais ou désactiverais le mode d'évitement des objets)
 Position 1 : Apostrophe not preceded by \ (in Si tu me presses, je t'enseignerais comment connecter mes broches)
 Position 1 : Apostrophe not preceded by \ (in Supprimer l'autorisation d'activer ou de désactiver le Bluetooth automatiquement pour économiser la batterie)
 Position 1 : Apostrophe not preceded by \ (in Afficher les messages d'aide sur l'usage de l'application)
 Position 1 : Apostrophe not preceded by \ (in Supprimer l'autorisation du Bluetooth)
 Position 1 : Apostrophe not preceded by \ (in Afficher les messages d'aide)

As I prefer letting you as the contributor, please fix that problem and make another pull request. 

Also, if you want a full french translation of the app, you can make a pull request to the comunication library (droid2ino) too if you want. You can find the repository of that library here:

https://github.com/bq/droid2ino

Thanks a lot!

**Comment by guyou** [comment]
Thanks for the feedback. I did the changes, but I'm unable to check (I do not have Android, but a BQ's Aquaris with Ubuntu ;-)). So I hope this is right now.

**Comment by yamidragut** [comment]
I have tested it and everything is ok! 

Tomorrow I will upload a new version to the play store with another minor changes. 
Thanks for your translation! ^^

As I told you yesterday, if you want to be the controbutor of the french translation of RoboPad++, please do a pull request in that repository too. 
RoboPad++ is another version of RoboPad but with the functionallity of programming the robot movements, I think your daughter will enjoy that a lot too ^^

Thanks again!

**Pull request merged**
